services:
  frontend:
    container_name: frontend
    image: fueled-fun:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-tier
    environment:
      API_BASE_URL: http://backend:8080

  backend:
    container_name: backend
    image: fueled-fun:backend
    networks:
      - frontend-tier

networks:
  frontend-tier: